# Declare images used by this game.
image bg gate = "bg/gates/gate4.png"
image bg forest = "bg/forest/forestpath2.png"
image bg temple = "bg/forest/foresttemple.png"
image bg castle1 = "bg/buildings/castle.png"
image bg castle2 = "bg/buildings/castle2.png"
image bg church = "bg/buildings/church.png"
image bg church2 = "bg/buildings/church2.png"
image bg church3 = "bg/buildings/church3.png"
image bg church4 = "bg/buildings/church4.png"
image bg library = "bg/buildings/library.png"
image bg shrine = "bg/buildings/shrine.png"
image bg tower = "bg/buildings/tower.jpg"
image bg village = "bg/buildings/village.png"
